#!/bin/sh

echo "🔒 Running security checks..."

echo "1/3 Checking secrets with Gitleaks..."

gitleaks detect --source . --no-banner

if [ $? -ne 0 ]; then
  echo "❌ Gitleaks found secrets. Commit blocked."
  exit 1
fi


echo "2/3 Checking secrets with TruffleHog..."

trufflehog filesystem . --results=verified,unknown

if [ $? -ne 0 ]; then
  echo "❌ TruffleHog found secrets. Commit blocked."
  exit 1
fi


echo "3/3 Checking code security with Semgrep..."

semgrep --config auto

if [ $? -ne 0 ]; then
  echo "❌ Semgrep found security issues. Commit blocked."
  exit 1
fi


echo "✅ Security checks passed."