name: Secure Release Pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write


jobs:
  release:

    name: Build and Secure Release

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0


      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Run Semgrep
        uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d


      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@c07df6fec6fa692e6fd1200d50aaa1fdd66f03c8
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true


      - name: Build application
        run: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found, skipping."
          fi


      - name: Generate artifact
        run: |
          mkdir -p release
          rsync -av \
            --exclude=.git \
            --exclude=release \
            ./ release/


      - name: Upload release artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: application-release
          path: release/


      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@96b4a1ef7235a096b17240c259729fdd70c83d45
        with:
          subject-path: release/**