name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches:
      - main


permissions: read-all


jobs:
  scorecard:

    name: Scorecard analysis

    runs-on: ubuntu-latest

    permissions:
      security-events: write
      id-token: write
      contents: read


    steps:

      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          persist-credentials: false


      - name: Run Scorecard
        uses: ossf/scorecard-action@0864cf9c5f3c9e7e7b6f5f9f7e5c2b1a9c0d8e7f
        with:
          results_file: results.sarif
          publish_results: true


      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@a65a038433a26f4363cf9f029e3b9ceac831ad5d
        with:
          sarif_file: results.sarif